module.exports = {
  apps: [
    {
      name: "signal-server",
      cwd: "/opt/trading-bot/Facebook",
      script: "/opt/trading-bot/deploy/runtime/python3.sh",
      args: "signal_server.py",
      interpreter: "none",
      env: {
        BEHIND_PROXY: "1",
        VENV_PYTHON: "/opt/trading-bot/venv/bin/python3",
        SIGNAL_LOG_FILE: "/var/lib/trading-bot/signal_log.txt",
        SIGNAL_QUEUE_FILE: "/var/lib/trading-bot/signal_queue.json",
        FACEBOOK_JOBS_DIR: "/var/lib/trading-bot/facebook-jobs",
        FACEBOOK_GROUPS_FILE: "/var/lib/trading-bot/facebook/fb_my_groups.xlsx",
        FACEBOOK_SESSION_FILE: "/var/lib/trading-bot/facebook/fb_session.json",
        FACEBOOK_POST_LOG: "/var/lib/trading-bot/facebook/post_log.xlsx",
        FACEBOOK_HEADLESS: "1",
      },
      autorestart: true,
      max_restarts: 20,
      restart_delay: 5000,
    },
    {
      name: "signal-engine",
      cwd: "/opt/trading-bot",
      script: "/opt/trading-bot/deploy/runtime/python3.sh",
      args: "run_engine.py",
      interpreter: "none",
      env_file: "/opt/trading-bot/.env",
      autorestart: true,
      max_restarts: 20,
      restart_delay: 10000,
    },
    {
      name: "dashboard",
      cwd: "/opt/trading-bot/dashboard",
      script: "/opt/trading-bot/deploy/runtime/gunicorn.sh",
      args: "-w 1 --threads 4 -b 0.0.0.0:8080 --timeout 120 server:app",
      interpreter: "none",
      env: {
        BOT_ROOT: "/opt/trading-bot",
        BOT_DATA_ROOT: "/var/lib/trading-bot",
        ENV_FILE: "/opt/trading-bot/.env",
        DASHBOARD_USERNAME: "admin",
        DASHBOARD_PASSWORD: "tradingbot2026",
        DEPLOY_BRANCH: "main",
        DASHBOARD_PORT: "8080",
        BEHIND_PROXY: "1",
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
